version: '3'
services:
  db_postgresql_users:
    container_name: "users_db"
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: usersPasswd
      POSTGRES_USER: usersUser
      POSTGRES_DB: usersDb

  db_postgresql_users_secondary:
    container_name: "users_db_secondary"
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: usersPasswd
      POSTGRES_USER: usersUser
      POSTGRES_DB: usersDbSecondary
