version: '3'
services:
  db_postgresql_accounts:
    container_name: "accounts_db"
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: accountsPasswd
      POSTGRES_USER: accountsUser
      POSTGRES_DB: accountsDb
