spring:
  application:
    name: transactions-server
  profiles:
    active: development
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        transaction-responses:
          destination: transactions
          contentType: application/json
        transaction-requests:
          destination: transactions
          contentType: application/json

management:
  endpoints:
    web:
      exposure:
        include: '*'

# ACTUATOR INFO
info:
  app:
    name: "Transactions server"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

eureka:
  client: ${eureka-client}

feign:
  hystrix:
    enabled: true
