spring:
  application:
    name: cards-server
  profiles:
    active: development

management:
  endpoints:
    web:
      exposure:
        include: '*'

# ACTUATOR INFO
info:
  app:
    name: "Cards server"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://admin-server:8761}/eureka/

feign:
  hystrix:
    enabled: true
